### ISSUE TITLE
Test Coverage - LDAPPropertyProcessor

### ISSUE THREAD

**Issue by ddlees** [BloodHoundAD/SharpHoundCommon#15]
Achieve +90% line coverage for `SharpHoundCommonLib.Processors.LDAPPropertyProcessor`

**Comment by rvazarkar** [comment]
This is currently sitting around 74%, but most of that is the ParseAllProperties function. Most of the other critical paths have been tested. Leaving this open for future stuff, but a good chunk of this is done
