### ISSUE TITLE
GPOLocalGroup check does not seem to evaluate Security Filter with Deny Apply

### ISSUE THREAD

**Issue by hendrik-smith** [BloodHoundAD/SharpHoundCommon#31]
I am finding the AdminTo edge for an AD group to several Computer objects in a SharpHound scan run with DCOnly option.
The only place I can see where this may come from is a GPO that is linked to the OU containing the Computer account - this GPO adds the AD group to the local Administrators group via Restricted Groups.
The issue is that on this GPO, I have security filtering that denies GPO Apply rights to an AD group that the Computer is a member of.  I can see on the Computer itself that his GPO is not applied (Security Filtering).
Can you confirm that this security filtering is not taken into account when evaluating this edge in SharpHound scans?  At the moment my BloodHound interface shows that there is a path from this AD group via its AdminTo edge on this Computer.

**Comment by rvazarkar** [comment]
This is a known problem, The complexity of applying GPO filtering is too high for us to implement it completely. We don't apply any sort of security filtering to it.
