### ISSUE TITLE
Publish latest version to NuGet.org

### ISSUE THREAD

**Issue by 0xd6cb6d73** [BloodHoundAD/SharpHoundCommon#91]
Hello,

Would it be possible to upload the latest version of SharpHoundCommon to nuget.org ? SharpHound 2.0.2 breaks with 3.0.8.

Thanks in advance.

**Comment by StephenHinck** [comment]
Nuget began flagging SharpHoundCommon as malware. We've had to switch to hosting our own nuget repo at https://s3.amazonaws.com/bloodhound-ad/index.json
